# fly.toml app configuration file generated for websockets-undertow-cask-repro on 2024-09-23T09:22:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'websockets-undertow-cask-repro'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 9191
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
